name: CloudMart CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pytest
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest
  
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Python syntax
        run: python3 -m py_compile app.py

  info:
    runs-on: ubuntu-latest

    env:
      APP_ENV: ci

    steps:
      -name: Show Environment
       run: echo "Environment is $APP_ENV"

      -name: Show Git commit
       run: echo "Commit is ${{ github.sha }}"

      -name: Main branch message
       if: github.ref == 'refs/head/main'
       run: echo "This workflow has triggered from main"
