name: CloudMart CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Run tests
        run: python3 -m pytest
